CREATE TABLE IF NOT EXISTS game_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  room_id TEXT NOT NULL,
  player_score INTEGER NOT NULL DEFAULT 0,
  ai_score INTEGER NOT NULL DEFAULT 0,
  winner TEXT NOT NULL,
  subject_cards_used TEXT NOT NULL,
  started_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME
);

CREATE TABLE IF NOT EXISTS questions_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  room_id TEXT NOT NULL,
  subject TEXT NOT NULL,
  level TEXT NOT NULL,
  question_hash TEXT NOT NULL,
  result TEXT NOT NULL,
  answered_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
